name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: ✨ Stargazers
        uses: lowlighter/metrics@latest
        with:
          user: saksh1013-coder
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.stargazers.svg
          base: ""
          plugin_stargazers: yes
          output_action: commit
