name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: ✨ Stargazers
        uses: lowlighter/metrics@master
        with:
          user: saksh1013-coder
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.stargazers.svg
          base: ""
          plugin_stargazers: yes
          output_action: commit
          delay: 120
          plugins_errors_fatal: yes
