name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-22.04

    steps:
      - name: ✨ Stargazers
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          output_action: commit
